"""When the DAG asks for manifests, and when it must not.

The tree is generated by the control plane; the DAG only asks for it. So what is
tested here is the asking: after a build that succeeded, with the image that
build produced — never after one that failed. A blueprint that does not build
asks before its first deploy, with the image the developer supplied.
"""

from __future__ import annotations

import sys
import unittest
from pathlib import Path
from unittest import mock

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT / "orchestrator" / "dags"))

import factory  # noqa: E402

SPEC = {
    "blueprint": "foo",
    "answers": {"app_name": "bar"},
    "kustomize": "kustomize/overlays/{environment}",
}


class AfterBuild(unittest.TestCase):

    # Catches: a tree generated for an image that was never built.
    def test_a_failed_build_asks_for_no_manifests(self):
        with mock.patch.object(factory.factory_scaffold, "build",
                               side_effect=RuntimeError("docker build failed")), \
                mock.patch.object(factory.factory_manifests, "generate") as generate:
            with self.assertRaises(RuntimeError):
                factory._build(spec=SPEC, spec_id="spec-one")
        generate.assert_not_called()

    # Catches: the tree naming an image other than the one just built.
    def test_a_build_asks_for_manifests_naming_its_image(self):
        built = {"image": "foo/bar:0123456789ab", "loaded_into": "factory", "from": "bar.git"}
        with mock.patch.object(factory.factory_scaffold, "build", return_value=built), \
                mock.patch.object(factory.factory_manifests, "generate") as generate:
            factory._build(spec=SPEC, spec_id="spec-one")
        generate.assert_called_once_with("spec-one", "foo/bar:0123456789ab")


class BeforeFirstDeploy(unittest.TestCase):

    # Catches: a blueprint with no build step never getting a tree, or getting
    # one at submission. It asks at its first deploy, with the answered image.
    def test_a_supplied_image_is_asked_for_before_the_first_deploy(self):
        spec = {
            "blueprint": "deploy-service",
            "answers": {"app_name": "hello", "image": "ghcr.io/acme/hello@sha256:abc"},
            "kustomize": "kustomize/overlays/{environment}",
        }
        with mock.patch.object(factory.factory_manifests, "generate") as generate, \
                mock.patch.object(factory.factory_manifests, "exists", return_value=False), \
                mock.patch.object(factory, "_render_and_apply", return_value={}):
            factory._apply(spec=spec, spec_id="spec-two",
                           environment="staging", namespace="payments-staging")
        generate.assert_called_once_with("spec-two", "ghcr.io/acme/hello@sha256:abc")


if __name__ == "__main__":
    unittest.main()
