apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: payments-qa
resources:
  - ../../base
replicas:
  - name: demo
    count: 1
labels:
  - includeSelectors: false
    includeTemplates: true
    pairs:
      factory.team: payments
      factory.spec: spec-3fd4cf68
      factory.blueprint: hello-fork
