apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: payments-production
resources:
  - ../../base
replicas:
  - name: multi-stage-app
    count: 2
labels:
  - includeSelectors: false
    includeTemplates: true
    pairs:
      factory.team: payments
      factory.spec: spec-6b3c8269
      factory.blueprint: hello-fork
patches:
  - target:
      kind: Deployment
      name: multi-stage-app
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/resources
        value:
          requests:
            cpu: 200m
            memory: 256Mi
          limits:
            cpu: 1000m
            memory: 512Mi
