"""What the generated DAGs call.

Each callable opens the shared store, records what it did there and closes it.
Airflow runs tasks in separate processes, so a connection per call is the honest
shape; the store is a file both this and the control plane open.

`request_action` still decides for itself whether an action is permitted, by
checking the spec's own boundaries. That is the next thing to change: the
decision belongs to a policy engine the worker asks, because a worker that
authorises itself is not a control plane.
"""

from __future__ import annotations

import os
import subprocess
from datetime import datetime, timezone
from pathlib import Path

from airflow.exceptions import AirflowException

import factory_db
import factory_manifests
import factory_metrics
import factory_scaffold
import factory_policy

FACTORY_ROOT = Path(os.environ.get(
    "FACTORY_ROOT",
    Path(__file__).resolve().parents[2],
))


def _now() -> str:
    return datetime.now(timezone.utc).isoformat(timespec="seconds").replace("+00:00", "Z")


def _action_for(spec, environment):
    """The action this spec performs in one environment."""
    for step in spec.get("sequence", []):
        if step.get("environment") == environment and step.get("action"):
            return step["action"]
    raise ValueError(f"this spec does nothing in {environment}")


def _step_for(spec, action, environment):
    """Find the step this task was generated from."""
    for index, step in enumerate(spec.get("sequence", [])):
        if step.get("action") == action and step.get("environment") == environment:
            return index, step
    raise ValueError(f"no {action} step for {environment} in this spec")


def _apply(spec, spec_id, environment, namespace, **_):
    """Render this spec's own overlay and apply it, generating the tree first if
    the run has not yet.

    A blueprint that builds has its tree generated by the build step. One whose
    developer supplied the image has no build, so its first deploy asks for the
    tree with that image — one path to the tree for both, and never before the
    run reaches it.
    """
    if not factory_manifests.exists(spec_id):
        image = spec["answers"].get("image")
        if not image:
            raise ValueError(
                f"{spec_id} has no manifests and no image to generate them from;"
                " a blueprint that builds must build before it deploys")
        factory_manifests.generate(spec_id, image)
    return _render_and_apply(spec, spec_id, environment, namespace)


def _render_and_apply(spec, spec_id, environment, namespace):
    """Render this spec's own overlay and apply it."""
    overlay = FACTORY_ROOT / "deployments" / spec_id / \
        spec["kustomize"].replace("{environment}", environment)
    if not overlay.is_dir():
        raise ValueError(f"no overlay at {overlay}")

    rendered = subprocess.run(
        ["kubectl", "kustomize", str(overlay)], capture_output=True, text=True)
    if rendered.returncode != 0:
        raise RuntimeError(f"kustomize failed: {rendered.stderr.strip()}")

    subprocess.run(
        ["kubectl", "create", "namespace", namespace],
        capture_output=True, text=True)          # already exists is fine

    applied = subprocess.run(
        ["kubectl", "apply", "-n", namespace, "-f", "-"],
        input=rendered.stdout, capture_output=True, text=True)
    if applied.returncode != 0:
        raise RuntimeError(applied.stderr.strip())

    lines = [line for line in applied.stdout.strip().split("\n") if line]
    print(f"[factory] applied to {namespace}")
    for line in lines:
        print(f"[factory]   {line}")
    return {"namespace": namespace, "applied": lines}


def _scaffold(spec, spec_id, **_):
    """Create the microservice this deployment spec is for."""
    result = factory_scaffold.scaffold(
        app_name=spec["answers"]["app_name"],
        spec_id=spec_id,
        blueprint=spec["blueprint"],
        port=spec["answers"].get("port", 3000),
    )
    print(f"[factory] scaffolded {result['repo']} at {result['commit'][:8]}")
    print(f"[factory]   {result['clone']}")
    return result


def _build(spec, spec_id, **_):
    """Build the scaffolded repository, then ask for manifests naming the image.

    In that order, and only on success: a build that fails raises before the
    manifests are asked for, so no tree names an image that was never built.
    """
    result = factory_scaffold.build(
        blueprint=spec["blueprint"], app_name=spec["answers"]["app_name"])
    print(f"[factory] built {result['image']} and loaded it into"
          f" {result['loaded_into']}")

    generated = factory_manifests.generate(spec_id, result["image"])
    print(f"[factory] manifests for {spec_id} name {result['image']}")
    return dict(result, manifests=generated)


# What this orchestrator knows how to do. An action not named here is refused,
# which is the difference between a factory that cannot do something and one
# that pretends to.
HANDLERS = {
    "scaffold": _scaffold,
    "build": _build,
    "deploy": _apply,
    "promote": _apply,
}


def request_action(spec_id, team, action, environment, step_index, **_):
    """Carry out one action, if the policy engine permits it.

    The worker decides nothing. It states what it means to do and is told yes,
    no, or that the engine cannot tell — and cannot_tell refuses, because a
    control plane that acts when it cannot reach its policy has none.

    The spec's boundaries are not checked here any more. They are checked by the
    policy, against the same spec, from the engine's own copy. Checking them in
    both places would be one rule written twice, and the copy that drifts is the
    one nobody is looking at. What this buys beyond the old check is the gate: a
    run posted straight at the promotion stage is refused here, because the
    engine holds no approval for it.

    The kustomize tree was generated beside the spec at submission and belongs
    to it alone, so there is no shared overlay for anyone to edit between
    submission and apply. Rendering happens here rather than at submission
    because the kustomization is the editable artifact; a stored manifest would
    have to be changed as raw Kubernetes YAML.
    """
    connection = factory_db.open_db()
    try:
        spec = factory_db.read_spec(connection, spec_id)

        # Kubernetes is the only target this knows how to realise. A spec naming
        # another one is refused here rather than half-applied: the failure
        # belongs at the point where the handler would be chosen, not inside a
        # kubectl call that was never the right tool.
        target = spec.get("type")
        if target != "k8s":
            raise ValueError(
                f"{spec_id} targets {target!r}, and this orchestrator only realises 'k8s'")

        decision = factory_policy.decide(spec_id, action, environment)
        if decision["result"] != "allow":
            factory_db.append_audit(connection, {
                "spec_id": spec_id,
                "at": _now(),
                "principal": {"id": "airflow-worker", "type": "agent", "team": team},
                "action": action,
                "target": {"environment": environment},
                "decision": decision["result"],
                "reason": decision["reason"],
            })
            print(f"[factory] {action} to {environment} refused:"
                  f" {decision['result']} — {decision['reason']}")
            raise PermissionError(
                f"{decision['result']}: {decision['reason']}")

        index, step = _step_for(spec, action, environment)
        namespace = step.get("namespace")

        handler = HANDLERS.get(action)
        if handler is None:
            # Every action used to fall through to kubectl apply, so an action
            # the factory had no idea how to perform quietly re-applied the
            # manifests and reported success. An action with no handler is a
            # blueprint asking for something this cannot do.
            raise ValueError(
                f"{action} has no handler; this orchestrator can perform "
                + ", ".join(sorted(HANDLERS)))

        outcome = handler(spec=spec, spec_id=spec_id, team=team,
                          action=action, environment=environment,
                          namespace=namespace, step=step)

        factory_db.append_audit(connection, {
            "spec_id": spec_id,
            "at": _now(),
            "principal": {"id": "airflow-worker", "type": "agent", "team": team},
            "action": action,
            "target": {"environment": environment, "namespace": namespace},
            "decision": "allow",
            # the position in the spec's own sequence
            "reason": f"step {index} of the spec's sequence; {decision['reason']}",
            "detail": outcome,
        })
        return outcome
    finally:
        connection.close()


def provision_observability(spec_id, team, environment, **_):
    """Make this deployment measurable, before anything is judged.

    The observability stack is applied here rather than assumed to exist,
    because a blueprint that declares acceptance is a blueprint that needs
    something able to answer it. Applying is idempotent; the part that does work
    every time is waiting until this deployment's own pods are being scraped.

    A spec with no acceptance criteria still gets this. The evidence is worth
    collecting whether or not anything is currently judged against it, and a
    blueprint that adds a criterion later should not find the history empty.
    """
    connection = factory_db.open_db()
    try:
        spec = factory_db.read_spec(connection, spec_id)
        _, step = _step_for(spec, _action_for(spec, environment), environment)
        namespace = step["namespace"]

        stack = factory_metrics.ensure_prometheus()
        print(f"[factory] observability ready at {stack['url']}")

        target = factory_metrics.wait_for_target(spec_id, namespace)
        print(f"[factory] scraping {target['targets_up']} pod(s) of {spec_id}"
              f" in {namespace}")

        # The acceptance block is a set of thresholds, so it becomes alerting
        # rules. Nothing evaluates them here: a threshold is crossed whenever it
        # is crossed, and asking once at deploy time would be asking about a
        # deployment nobody has used yet.
        rules = factory_metrics.install_rules(spec)
        print(f"[factory] {rules['rules']} alert rule(s) generated from the"
              f" acceptance block")

        factory_db.append_audit(connection, {
            "spec_id": spec_id,
            "at": _now(),
            "principal": {"id": "airflow-worker", "type": "agent", "team": team},
            "action": "provision_observability",
            "target": {"environment": environment, "namespace": namespace},
            "decision": "allow",
            "reason": f"{target['targets_up']} pod(s) scraped and {rules['rules']}"
                      f" alert rule(s) installed from the acceptance block",
            "detail": {
                "applied": stack["applied"],
                "prometheus": stack["url"],
                "alert_rules": rules,
            },
        })
        return {"targets": target, "rules": rules}
    except Exception as error:
        factory_db.append_audit(connection, {
            "spec_id": spec_id,
            "at": _now(),
            "principal": {"id": "airflow-worker", "type": "agent", "team": team},
            "action": "provision_observability",
            "target": {"environment": environment},
            "decision": "error",
            "reason": str(error)[:300],
        })
        raise
    finally:
        connection.close()


def open_gate(spec_id, team, gate, approver_role, step_index, **_):
    """Record that a decision is needed. Called once, by the sensor's first poke.

    Opening is idempotent, and that matters: the sensor pokes every thirty
    seconds, and each poke must not reset a gate somebody has already decided or
    lose the name of whoever decided it.
    """
    connection = factory_db.open_db()
    try:
        state = factory_db.open_approval(
            connection, spec_id, gate, approver_role, spec_id, _now())

        if state == "pending":
            factory_db.append_audit(connection, {
                "spec_id": spec_id,
                "at": _now(),
                "principal": {"id": "airflow-worker", "type": "agent", "team": team},
                "action": "open_gate",
                "target": {"gate": gate, "step_index": step_index},
                "decision": "allow",
                "reason": f"{gate} needs a {approver_role}; this run waits here",
            })
            print(f"[factory] gate {gate} open, waiting for a {approver_role}")
        return state
    finally:
        connection.close()


def gate_passed(spec_id, team, gate, approver_role, step_index, **_):
    """Whether this gate has been approved. The sensor's poke.

    Returning False frees the worker until the next poke, so a gate open for a
    week costs a row in the metadata database rather than a slot. The decision
    itself is the control plane's: this only reads it.

    A rejection does not return False forever — that would wait out the timeout
    and report the gate as slow rather than as refused. It raises, so the run
    stops and says why.
    """
    connection = factory_db.open_db()
    try:
        row = factory_db.read_approval(connection, spec_id, gate)
        if row is None:
            # first poke: nobody can decide a gate that has not been opened
            open_gate(spec_id=spec_id, team=team, gate=gate,
                      approver_role=approver_role, step_index=step_index)
            return False

        if row["state"] == "approved":
            print(f"[factory] {gate} approved by {row['decided_by']}")
            return True

        if row["state"] == "rejected":
            factory_db.append_audit(connection, {
                "spec_id": spec_id,
                "at": _now(),
                "principal": {"id": "airflow-worker", "type": "agent", "team": team},
                "action": "gate_rejected",
                "target": {"gate": gate},
                "decision": "deny",
                "reason": f"{gate} was rejected by {row['decided_by']}",
            })
            raise AirflowException(
                f"{gate} was rejected by {row['decided_by']}; this run stops here")

        return False
    finally:
        connection.close()
