"""Asking the control plane for a spec's manifests.

The tree is generated by the control plane, not here: the deployments directory
keeps one writer and one generator. The DAG asks when it has an image — after
build, or before the first deploy for a blueprint whose image was supplied.

OPEN: the request carries no credential. The endpoint is not authenticated yet;
the intended shape is a run-scoped token issued for this spec.
"""

from __future__ import annotations

import json
import os
import urllib.error
import urllib.request
from pathlib import Path

CONTROL_PLANE_URL = os.environ.get("FACTORY_API", "http://127.0.0.1:4000")
TIMEOUT_SECONDS = 30

FACTORY_ROOT = Path(os.environ.get(
    "FACTORY_ROOT",
    Path(__file__).resolve().parents[2],
))


def exists(spec_id: str) -> bool:
    """Whether this spec's tree has been generated."""
    return (FACTORY_ROOT / "deployments" / spec_id / "kustomize").is_dir()


def generate(spec_id: str, image: str) -> dict:
    """Ask for the tree, naming the image. Raises unless it exists for that image.

    A 409 for the same image is a retry finding its own earlier success, and is
    not a failure. A 409 for another image is: the tree on disk names something
    other than what this run built, and deploying it would deploy the wrong thing.
    """
    request = urllib.request.Request(
        f"{CONTROL_PLANE_URL}/api/deployments/{spec_id}/manifests",
        data=json.dumps({"image": image}).encode("utf-8"),
        headers={"content-type": "application/json"},
        method="POST",
    )

    try:
        with urllib.request.urlopen(request, timeout=TIMEOUT_SECONDS) as response:
            return json.loads(response.read().decode("utf-8"))
    except urllib.error.HTTPError as error:
        body = _body(error)
        if error.code == 409 and body.get("image") == image:
            return {"spec_id": spec_id, "image": image, "already_generated": True}
        raise RuntimeError(
            f"manifests for {spec_id} were refused ({error.code}):"
            f" {body.get('error', 'no reason given')}") from error
    except (urllib.error.URLError, TimeoutError, OSError) as error:
        raise RuntimeError(
            f"the control plane at {CONTROL_PLANE_URL} could not be reached: {error}") from error


def _body(error: urllib.error.HTTPError) -> dict:
    try:
        return json.loads(error.read().decode("utf-8"))
    except (ValueError, OSError):
        return {}
