# generated by datamodel-codegen:
#   filename:  spec.yaml
#   timestamp: 2026-09-18T16:45:06+00:00

from __future__ import annotations

from dataclasses import dataclass
from enum import Enum
from typing import TypeAlias

SnapshotId: TypeAlias = str
"""
Opaque identifier for this collection entry; links metadata to its payload.
"""


@dataclass
class KeyValueEntry:
    Key: str
    Value: str


KeyValueMap: TypeAlias = dict[str, str]


class ResourceType(Enum):
    aws_instance = 'aws_instance'
    aws_db_instance = 'aws_db_instance'


class Kind(Enum):
    Deployment = 'Deployment'
    ReplicaSet = 'ReplicaSet'
    Pod = 'Pod'
    Node = 'Node'


@dataclass
class Scope:
    """
    The boundaries and filters of this collection.
    """

    account_id: str | None = None
    """
    Constrains cloud and state collections.
    """
    region: str | None = None
    """
    Constrains cloud and state collections.
    """
    environment: str | None = None
    """
    The authoritative environment classification for that cloud, state, or Kubernetes collection.
    """
    resource_types: list[ResourceType] | None = None
    """
    Constrains cloud and state collections.
    """
    workspace_id: str | None = None
    """
    Further bounds a state extract.
    """
    instance_ids: list[str] | None = None
    """
    An additional inventory filter.
    """
    cluster_id: str | None = None
    """
    Bounds a Kubernetes collection.
    """
    namespaces: list[str] | None = None
    """
    Namespace filtering applies to namespaced kinds; Nodes are cluster-scoped.
    """
    kinds: list[Kind] | None = None
    """
    Bounds a Kubernetes collection.
    """
    environments: list[str] | None = None
    """
    Catalog rows declare their own environment, within this list.
    """


class SourceFamily(Enum):
    aws = 'aws'
    terraform = 'terraform'
    kubernetes = 'kubernetes'
    catalog = 'catalog'


class Format(Enum):
    json = 'json'
    csv = 'csv'


class Status(Enum):
    success = 'success'
    not_provided = 'not_provided'


class Coverage(Enum):
    complete = 'complete'
    unknown = 'unknown'


@dataclass
class Snapshot:
    """
    One logical collection.
    """

    snapshot_id: SnapshotId
    source_family: SourceFamily
    source_instance_id: str
    """
    The logical collector, workspace connection, or catalog across collections.
    """
    tenant_id: str
    """
    Trusted internal tenant context for this collection.
    """
    payload_path: str | None
    """
    Relative file path; unavailable input has a null path.
    """
    format: Format
    observed_at: str | None
    """
    When the collector actually observed the supplied values.
    """
    exported_at: str | None
    """
    When the extract was packaged; separate from observation time.
    """
    freshness_budget_seconds: int
    """
    Maximum acceptable observation age at as_of; equality is within budget.
    """
    status: Status
    coverage: Coverage
    scope: Scope


@dataclass
class QueryDefaults:
    """
    An initial request. Default query parameters.
    """

    tenant_id: str
    environment: str
    application_name: str


@dataclass
class Manifest:
    extract_version: str
    schema_version: int
    as_of: str
    """
    Fixed evaluation time. Use this regardless of when the exercise is run.
    """
    extract_notes: str
    tenants: list[str]
    query_defaults: QueryDefaults
    snapshots: list[Snapshot]
    description: str | None = None


@dataclass
class AwsInstanceState:
    Name: str


@dataclass
class AwsInstance:
    InstanceId: str
    State: AwsInstanceState
    PrivateIpAddress: str | None = None
    """
    A network address, not a provider identifier.
    """
    VpcId: str | None = None
    """
    Refers to network scope.
    """
    Tags: list[KeyValueEntry] | None = None
    """
    Normalized by the extractor to an array of Key/Value objects. Name is a display label; Environment is a source tag; operator_team, when present, is that source's statement about infrastructure operation. Omitted tags are not empty-string claims.

    """


@dataclass
class AwsDatabase:
    DBInstanceIdentifier: str
    DBInstanceArn: str
    """
    Database ARNs are supplied directly.
    """
    DBInstanceStatus: str
    Tags: list[KeyValueEntry] | None = None


@dataclass
class AwsCollection:
    """
    An empty array applies only to this collection's declared resource-type scope.
    """

    snapshot_id: SnapshotId
    instances: list[AwsInstance]
    databases: list[AwsDatabase]


@dataclass
class AwsInventory:
    collections: list[AwsCollection]


@dataclass
class TerraformValues:
    """
    Identifies the referenced provider object.
    """

    id: str
    arn: str | None = None
    tags: KeyValueMap | None = None
    """
    A string-to-string mapping, unlike the AWS tag array.
    """


class Mode(Enum):
    """
    managed denotes a managed-resource record; data denotes a data-source reference.

    """

    managed = 'managed'
    data = 'data'


class Type(Enum):
    aws_instance = 'aws_instance'
    aws_db_instance = 'aws_db_instance'


@dataclass
class TerraformResource:
    address: str
    """
    The resource address within a workspace.
    """
    mode: Mode
    """
    managed denotes a managed-resource record; data denotes a data-source reference.

    """
    type: Type
    values: TerraformValues


@dataclass
class TerraformState:
    snapshot_id: SnapshotId
    lineage: str
    """
    Identifies the state lineage. Not a wall-clock time.
    """
    serial: int
    """
    That state's revision counter. Not a wall-clock time.
    """
    resources: list[TerraformResource]


@dataclass
class K8sOwnerReference:
    """
    Controller/lifecycle references, including target kind, name, and UID. ReplicaSets reference Deployments, and Pods reference ReplicaSets.

    """

    apiVersion: str
    kind: str
    name: str
    uid: str
    controller: bool | None = None


@dataclass
class K8sMetadata:
    name: str
    """
    Display names can be reused.
    """
    uid: str
    """
    Identifier of the object's incarnation.
    """
    namespace: str | None = None
    """
    Supplied for namespaced objects.
    """
    labels: KeyValueMap | None = None
    """
    Source labels where supplied.
    """
    ownerReferences: list[K8sOwnerReference] | None = None


@dataclass
class K8sSelector:
    matchLabels: KeyValueMap | None = None


@dataclass
class K8sSpec:
    """
    Selected workload specification fields.
    """

    replicas: int | None = None
    selector: K8sSelector | None = None
    nodeName: str | None = None
    """
    Pod. Name of its assigned Node in the same cluster.
    """
    providerID: str | None = None
    """
    Node. Optional provider reference, format aws:///<availability-zone>/<instance-id>. Does not encode the account. An omitted provider reference is not an empty instance identifier.

    """


@dataclass
class K8sAddress:
    type: str
    address: str


@dataclass
class K8sStatus:
    phase: str | None = None
    """
    Reported Pod phase.
    """
    addresses: list[K8sAddress] | None = None
    """
    Node. Reported addresses, including InternalIP.
    """


@dataclass
class K8sObject:
    """
    Selected fields only, with exactly the kinds listed in its manifest scope.
    """

    apiVersion: str
    kind: Kind
    metadata: K8sMetadata
    spec: K8sSpec | None = None
    status: K8sStatus | None = None


@dataclass
class K8sCollection:
    snapshot_id: SnapshotId
    items: list[K8sObject]


@dataclass
class K8sResources:
    collections: list[K8sCollection]


@dataclass
class ServiceCatalogRow:
    """
    CSV values are strings; blank cells mean not supplied, not an assertion that no team, workload, or dependency exists.

    """

    snapshot_id: SnapshotId
    """
    Manifest collection for this row.
    """
    service_id: str
    """
    Catalog application identifier within its tenant.
    """
    service_name: str
    """
    Application display name.
    """
    environment: str
    """
    Environment classification for this entry.
    """
    owner_team: str | None = None
    """
    Catalog statement of application-team responsibility.
    """
    cluster_id: str | None = None
    """
    A workload reference.
    """
    namespace: str | None = None
    """
    A workload reference.
    """
    deployment_name: str | None = None
    """
    A workload reference; refers to a Kubernetes Deployment.
    """
    declared_dependency_arn: str | None = None
    """
    A dependency stated by the catalog, when supplied.
    """
